services:
  backend:
    build: ./server
    container_name: shopsphere-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: shopsphere-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend